import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@scaffold-ui/components/styles.css";
import "@rainbow-me/rainbowkit/styles.css";
// should be last or use !important in styles
import "./globals.css";
import { ScaffoldEthAppWithProviders } from "./ScaffoldETHProvider";
import { ThemeProvider } from "./components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider enableSystem>
          <ScaffoldEthAppWithProviders>{children}</ScaffoldEthAppWithProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
